module.exports = {
  openapi: '3.0.0',
  info: {
    title: 'Stock Driver System API',
    version: '1.0.0',
    description: 'Inventory, driver stock requests, purchase orders, payments, and reports.'
  },
  servers: [{ url: '/api/v1' }],
  components: {
    securitySchemes: {
      bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' }
    }
  },
  security: [{ bearerAuth: [] }],
  paths: {
    '/auth/login': { post: { security: [], summary: 'Login', responses: { 200: { description: 'Login successful' } } } },
    '/auth/me': { get: { summary: 'Current user', responses: { 200: { description: 'Current user loaded' } } } },
    '/auth/me/profile': { patch: { summary: 'Update current user profile' } },
    '/auth/me/password': { patch: { summary: 'Change current user password' } },
    '/auth/logout': { post: { summary: 'Logout' } },
    '/users': { get: { summary: 'List users' }, post: { summary: 'Create user' } },
    '/users/{id}': { patch: { summary: 'Update user' } },
    '/users/{id}/status': { patch: { summary: 'Update user status' } },
    '/roles': { get: { summary: 'List roles' } },
    '/roles/{id}': { patch: { summary: 'Update role' } },
    '/permissions': { get: { summary: 'List permissions' } },
    '/roles/{id}/permissions': { get: { summary: 'Get role permissions' }, patch: { summary: 'Update role permissions' } },
    '/audit-logs': { get: { summary: 'List audit logs' } },
    '/categories': { get: { summary: 'List categories' }, post: { summary: 'Create category' } },
    '/categories/{id}': { patch: { summary: 'Update category' }, delete: { summary: 'Delete category' } },
    '/categories/{id}/status': { patch: { summary: 'Update category status' } },
    '/suppliers': { get: { summary: 'List suppliers' }, post: { summary: 'Create supplier' } },
    '/suppliers/{id}': { patch: { summary: 'Update supplier' }, delete: { summary: 'Delete supplier' } },
    '/suppliers/{id}/status': { patch: { summary: 'Update supplier status' } },
    '/items': { get: { summary: 'List items' }, post: { summary: 'Create item' } },
    '/items/{id}': { patch: { summary: 'Update item' }, delete: { summary: 'Delete item' } },
    '/items/{id}/status': { patch: { summary: 'Archive or restore item' } },
    '/items/low-stock': { get: { summary: 'List low stock items' } },
    '/stock-entries': { post: { summary: 'Add stock' } },
    '/stock-adjustments': { post: { summary: 'Adjust stock' } },
    '/stock-movements': { get: { summary: 'List stock movements' } },
    '/purchase-orders': { get: { summary: 'List purchase orders' }, post: { summary: 'Create purchase order' } },
    '/purchase-orders/{id}': { get: { summary: 'Get purchase order' }, patch: { summary: 'Update purchase order metadata' } },
    '/purchase-orders/{id}/receive': { post: { summary: 'Receive purchase order stock' } },
    '/purchase-orders/{id}/cancel': { post: { summary: 'Cancel purchase order' } },
    '/drivers': { get: { summary: 'List drivers' }, post: { summary: 'Create driver' } },
    '/drivers/{id}': { patch: { summary: 'Update driver' }, delete: { summary: 'Delete driver' } },
    '/drivers/{id}/status': { patch: { summary: 'Update driver status' } },
    '/drivers/{id}/balance': { get: { summary: 'Get driver balance' } },
    '/drivers/{id}/location-history': { get: { summary: 'Get driver location history' } },
    '/locations': { get: { summary: 'List locations' }, post: { summary: 'Create location' } },
    '/locations/{id}': { patch: { summary: 'Update location' } },
    '/locations/{id}/status': { patch: { summary: 'Update location status' } },
    '/commission-rules': { get: { summary: 'List commission rules' }, post: { summary: 'Create commission rule' } },
    '/commission-rules/{id}': { patch: { summary: 'Update commission rule' } },
    '/commission-rules/{id}/status': { patch: { summary: 'Update commission rule status' } },
    '/monthly-targets': { get: { summary: 'List monthly targets' }, post: { summary: 'Create monthly target' } },
    '/monthly-targets/{id}': { patch: { summary: 'Update monthly target' } },
    '/monthly-targets/{id}/status': { patch: { summary: 'Update monthly target status' } },
    '/stock-requests': { get: { summary: 'List stock requests' }, post: { summary: 'Create stock request' } },
    '/stock-requests/{id}': { get: { summary: 'Get stock request' }, patch: { summary: 'Update draft or pending stock request' } },
    '/stock-requests/{id}/accept': { post: { summary: 'Accept stock request' } },
    '/stock-requests/{id}/complete': { post: { summary: 'Complete stock request' } },
    '/stock-requests/{id}/cancel': { post: { summary: 'Cancel stock request' } },
    '/stock-requests/{id}/print': { post: { summary: 'Record stock request print attempt' } },
    '/payments': { get: { summary: 'List payments' }, post: { summary: 'Create payment' } },
    '/settings': { get: { summary: 'List settings' }, patch: { summary: 'Update settings' } },
    '/print/qz/certificate': { get: { summary: 'Get QZ Tray certificate' } },
    '/print/qz/sign': { post: { summary: 'Sign QZ Tray request' } },
    '/driver/me': { get: { summary: 'Get linked driver profile' } },
    '/driver/stock-requests': { get: { summary: 'List driver portal stock requests' } },
    '/driver/stock-requests/{id}': { get: { summary: 'Get driver portal stock request' } },
    '/driver/stock-requests/{id}/invoice-viewed': { post: { summary: 'Mark driver invoice viewed' } },
    '/driver/stock-requests/{id}/receipt': { post: { summary: 'Submit driver receipt confirmation' } },
    '/reports/dashboard': { get: { summary: 'Dashboard report' } },
    '/reports/inventory-summary': { get: { summary: 'Inventory summary report' } },
    '/reports/driver-balances': { get: { summary: 'Driver balances report' } },
    '/reports/payment-summary': { get: { summary: 'Payment summary report' } },
    '/reports/missing-payments': { get: { summary: 'Missing payments report' } },
    '/reports/purchase-summary': { get: { summary: 'Purchase summary report' } },
    '/reports/commission-summary': { get: { summary: 'Commission summary report' } },
    '/reports/target-kpis': { get: { summary: 'Target KPI report' } },
    '/reports/driver-payroll': { get: { summary: 'Driver payroll report' } },
    '/reports/drivers/detail': { get: { summary: 'Driver detail report overview' } },
    '/reports/drivers/{id}/detail': { get: { summary: 'Driver detail report' } }
  }
};
